# 配置端口
server:
  port: 8081
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.48.231:3306/smp?useUnicode=true&characterEncoding=utf8
      username: bi-read
      password: 973zNjy!JvTQ^4h2
      driver-class-name: com.mysql.jdbc.Driver
      db-type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  # xml文件路径
  mapper-locations: classpath:mapper/*.xml
  # 实体类路径
  type-aliases-package: com.example.paypalspringbootdemo.domain
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 是否开启缓存
    cache-enabled: false
  # 全局配置
  global-config:
    # 数据库字段驼峰下划线转换
    db-column-underline: true
    # id自增类型(数据库id自增)
    id-type: 0
paypal:
  clientId: Accc2b-eTxyx2dKsKdIpBvva8QXoQoa7LRW3T3Q-2tfEdJZZFvciC3v24ACUL6zkkrOhXPnRPW_2rStQ
  clientSecret: EKNzFPer8gFvSz9zuJGWycdc3G4dcy3Djcqw2XGuoO2TWE4VzmOsT3BSgyk1_QLGqT9Y8TsFUSasJAbk
  mode: live
  receiver:
    email: ""